# Generated by Django 2.2.16 on 2020-09-11 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 9, 30, 44, 118446, tzinfo=utc)),
        ),
    ]
