# Generated by Django 2.2.16 on 2020-09-10 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='server',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 14, 16, 50, 12666, tzinfo=utc)),
        ),
    ]
