# Generated by Django 2.2.16 on 2020-09-10 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import functools
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20200910_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 16, 23, 1, 241704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='secret',
            field=models.CharField(db_index=True, default=functools.partial(secrets.token_urlsafe, *(32,), **{}), max_length=100, unique=True),
        ),
    ]
