# Generated by Django 2.2.16 on 2020-09-10 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20200910_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 17, 28, 10, 987595, tzinfo=utc)),
        ),
    ]
